version: '3.8'
services:
  db_shortner:
    container_name: db_shortner
    image: postgres:alpine3.14
    restart: always
    environment:
      POSTGRES_DB: ${PG_DB}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata_shortner
    ports:
      - "5433:5432"
    volumes:
      - us_pgdata:/var/lib/postgresql/data
  backend:
    container_name: backend-container
    build:
      context: ./backend/app
#      dockerfile: backend/app/Dockerfile
    environment:
      HTTP_PORT: 8000
      DB_DSN: postgres://${PG_USER}:${PG_PASSWORD}@db_shortner:5432/${PG_DB}
    depends_on:
      - db_shortner
    ports:
      - "80:8000"
volumes:
  us_pgdata:
    name: us_pgdata
    driver: local