version: '3.8'
services:
  db:
    #    имя/хост контейнера
    container_name: db_shortner
    #    образ для создания
    image: postgres:alpine3.14
    #    если контейнер упал - всегда перзапустить
    restart: always
    #    настройки окружения для контейнера
    environment:
      POSTGRES_DB: ${PG_DB}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      #      указываем где хранить данные БД, ниже есть описание, что это папка монтируется к папке родительской ОС
      PGDATA: /var/lib/postgresql/data/pgdata_shortner
    ports:
      - "5433:5432"
    volumes:
      - shortner_pgdata:/var/lib/postgresql/data
  application:
    container_name: site
    build:
      context: ./backend/app
    environment:
      HTTP_PORT: 8000
      DB_DSN: postgres://${PG_USER}:${PG_PASSWORD}@db_shortner:5432/${PG_DB}
    depends_on:
      - db_shortner
    ports:
      - "80:8000"
volumes:
  shortner_pgdata:
    name: shortner_pgdata
    driver: local
