// Code generated by entc, DO NOT EDIT.

package shorturl

import (
	"time"
)

const (
	// Label holds the string label denoting the shorturl type in the database.
	Label = "short_url"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldURL holds the string denoting the url field in the database.
	FieldURL = "url"
	// FieldExpiredAt holds the string denoting the expired_at field in the database.
	FieldExpiredAt = "expired_at"
	// Table holds the table name of the shorturl in the database.
	Table = "short_urls"
)

// Columns holds all SQL columns for shorturl fields.
var Columns = []string{
	FieldID,
	FieldURL,
	FieldExpiredAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// URLValidator is a validator for the "url" field. It is called by the builders before save.
	URLValidator func(string) error
	// DefaultExpiredAt holds the default value on creation for the "expired_at" field.
	DefaultExpiredAt func() time.Time
)
