// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"log"

	"github.com/Z00mZE/url-shortner/ent/migrate"

	"github.com/Z00mZE/url-shortner/ent/urls"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"

	databaseSql "database/sql"
	_ "github.com/jackc/pgx/v4/stdlib"
	_ "github.com/lib/pq"
)

const PgPgx = "pgx"

var driverMap = map[string]string{
	PgPgx:            dialect.Postgres,
	dialect.MySQL:    dialect.MySQL,
	dialect.SQLite:   dialect.SQLite,
	dialect.Postgres: dialect.Postgres,
	dialect.Gremlin:  dialect.Gremlin,
}

type DBOption func(db *databaseSql.DB)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Urls is the client for interacting with the Urls builders.
	Urls *UrlsClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	cfg := config{log: log.Println, hooks: &hooks{}}
	cfg.options(opts...)
	client := &Client{config: cfg}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Urls = NewUrlsClient(c.config)
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options []Option, dbOption []DBOption) (*Client, error) {
	switch driverName {
	case PgPgx:
		db, err := databaseSql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}

		for _, opt := range dbOption {
			opt(db)
		}
		return NewClient(Driver(sql.OpenDB(driverMap[driverName], db))), nil
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:    ctx,
		config: cfg,
		Urls:   NewUrlsClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:    ctx,
		config: cfg,
		Urls:   NewUrlsClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Urls.
//		Query().
//		Count(ctx)
//
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.Urls.Use(hooks...)
}

// UrlsClient is a client for the Urls schema.
type UrlsClient struct {
	config
}

// NewUrlsClient returns a client for the Urls from the given config.
func NewUrlsClient(c config) *UrlsClient {
	return &UrlsClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `urls.Hooks(f(g(h())))`.
func (c *UrlsClient) Use(hooks ...Hook) {
	c.hooks.Urls = append(c.hooks.Urls, hooks...)
}

// Create returns a create builder for Urls.
func (c *UrlsClient) Create() *UrlsCreate {
	mutation := newUrlsMutation(c.config, OpCreate)
	return &UrlsCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Urls entities.
func (c *UrlsClient) CreateBulk(builders ...*UrlsCreate) *UrlsCreateBulk {
	return &UrlsCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Urls.
func (c *UrlsClient) Update() *UrlsUpdate {
	mutation := newUrlsMutation(c.config, OpUpdate)
	return &UrlsUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *UrlsClient) UpdateOne(u *Urls) *UrlsUpdateOne {
	mutation := newUrlsMutation(c.config, OpUpdateOne, withUrls(u))
	return &UrlsUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *UrlsClient) UpdateOneID(id int) *UrlsUpdateOne {
	mutation := newUrlsMutation(c.config, OpUpdateOne, withUrlsID(id))
	return &UrlsUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Urls.
func (c *UrlsClient) Delete() *UrlsDelete {
	mutation := newUrlsMutation(c.config, OpDelete)
	return &UrlsDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *UrlsClient) DeleteOne(u *Urls) *UrlsDeleteOne {
	return c.DeleteOneID(u.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *UrlsClient) DeleteOneID(id int) *UrlsDeleteOne {
	builder := c.Delete().Where(urls.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &UrlsDeleteOne{builder}
}

// Query returns a query builder for Urls.
func (c *UrlsClient) Query() *UrlsQuery {
	return &UrlsQuery{
		config: c.config,
	}
}

// Get returns a Urls entity by its id.
func (c *UrlsClient) Get(ctx context.Context, id int) (*Urls, error) {
	return c.Query().Where(urls.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *UrlsClient) GetX(ctx context.Context, id int) *Urls {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *UrlsClient) Hooks() []Hook {
	return c.hooks.Urls
}
