// Code generated by entc, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/Z00mZE/url-shortner/ent/schema"
	"github.com/Z00mZE/url-shortner/ent/urls"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	urlsFields := schema.Urls{}.Fields()
	_ = urlsFields
	// urlsDescURL is the schema descriptor for url field.
	urlsDescURL := urlsFields[0].Descriptor()
	// urls.URLValidator is a validator for the "url" field. It is called by the builders before save.
	urls.URLValidator = urlsDescURL.Validators[0].(func(string) error)
	// urlsDescExpiredAt is the schema descriptor for expired_at field.
	urlsDescExpiredAt := urlsFields[1].Descriptor()
	// urls.DefaultExpiredAt holds the default value on creation for the expired_at field.
	urls.DefaultExpiredAt = urlsDescExpiredAt.Default.(func() time.Time)
}
